name: Déployer vers GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload des fichiers vers Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Déploiement
        uses: actions/deploy-pages@v4
